<?php
namespace App\Services;
use App\Models\ProductModel;use App\Models\ProductPackageModel;use App\Models\ProductVariantModel;
class CartService
{
 private string $key='shopping_cart';
 public function raw():array{return (array)session($this->key);}
 public function addProduct(int $productId,?int $variantId,int $quantity):void{$p=(new ProductModel())->find($productId);if(!$p||$p['status']!=='active')throw new \RuntimeException('পণ্যটি পাওয়া যায়নি।');if($p['stock_type']==='variant'){if(!$variantId)throw new \RuntimeException('একটি অপশন নির্বাচন করুন।');$v=(new ProductVariantModel())->where(['id'=>$variantId,'product_id'=>$productId,'status'=>'active'])->first();if(!$v)throw new \RuntimeException('নির্বাচিত অপশনটি সঠিক নয়।');$max=(int)$v['stock_quantity'];}else{$variantId=null;$max=$p['manage_stock']&&!$p['allow_backorder']?(int)$p['stock_quantity']:PHP_INT_MAX;}$this->put(['item_type'=>'product','product_id'=>$productId,'variant_id'=>$variantId,'package_id'=>null],$quantity,$max);}
 public function addPackage(int $id,int $quantity):void{$p=(new ProductPackageModel())->find($id);if(!$p||$p['status']!=='active')throw new \RuntimeException('প্যাকটি পাওয়া যায়নি।');$this->put(['item_type'=>'package','product_id'=>null,'variant_id'=>null,'package_id'=>$id],$quantity,(new PackageService())->getPackageAvailableQuantity($id));}
 private function put(array $item,int $quantity,int $max):void{if($quantity<1)throw new \RuntimeException('পরিমাণ কমপক্ষে ১ হতে হবে।');$key=$this->itemKey($item);$cart=$this->raw();$new=$quantity+(int)($cart[$key]['quantity']??0);if($max<$new)throw new \RuntimeException('পর্যাপ্ত স্টক নেই। সর্বোচ্চ '.$max.'টি পাওয়া যাচ্ছে।');$item['quantity']=$new;$cart[$key]=$item;session()->set($this->key,$cart);}
 public function replace(array $quantities):void{$cart=$this->raw();foreach($quantities as $key=>$qty){if(isset($cart[$key]))$cart[$key]['quantity']=max(1,(int)$qty);}session()->set($this->key,$cart);$resolved=$this->resolve();if($resolved['errors'])throw new \RuntimeException(implode(' ',$resolved['errors']));}
 public function remove(string $key):void{$cart=$this->raw();unset($cart[$key]);session()->set($this->key,$cart);}
 public function clear():void{session()->remove($this->key);}
 public function count():int{return array_sum(array_column($this->raw(),'quantity'));}
 public function resolve(?array $source=null):array{$rows=[];$errors=[];$subtotal=0;foreach($source??$this->raw() as $key=>$item){$q=max(1,(int)$item['quantity']);if($item['item_type']==='package'){$row=(new ProductPackageModel())->find($item['package_id']);$max=$row&&$row['status']==='active'?(new PackageService())->getPackageAvailableQuantity((int)$row['id']):0;$price=(float)($row['package_price']??0);$name=$row['name']??'Unavailable package';$image=$row['main_image']??null;$variant=null;}else{$row=(new ProductModel())->find($item['product_id']);$variant=$item['variant_id']?(new ProductVariantModel())->where(['id'=>$item['variant_id'],'product_id'=>$item['product_id'],'status'=>'active'])->first():null;if(!$row||$row['status']!=='active'||($row['stock_type']==='variant'&&!$variant)){$max=0;$price=0;$name=$row['name']??'Unavailable product';$image=$row['main_image']??null;}else{$target=$variant?:$row;$price=(new ProductService())->effectivePrice($target);$max=$variant?(int)$variant['stock_quantity']:($row['manage_stock']&&!$row['allow_backorder']?(int)$row['stock_quantity']:PHP_INT_MAX);$name=$row['name'];$image=$row['main_image'];}}if($max<$q)$errors[]=$name.'-এর পর্যাপ্ত স্টক নেই।';$line=$price*$q;$subtotal+=$line;$rows[]=$item+['key'=>$key,'name'=>$name,'variant_name'=>$variant['variant_name']??null,'image'=>$image,'unit_price'=>$price,'subtotal'=>$line,'max'=>$max,'available'=>$max>=$q];}return ['items'=>$rows,'subtotal'=>$subtotal,'count'=>array_sum(array_column($rows,'quantity')),'errors'=>$errors];}
 public function one(array $item):array{return $this->resolve([$this->itemKey($item)=>$item]);}
 private function itemKey(array $i):string{return $i['item_type']==='package'?'package:'.$i['package_id']:'product:'.$i['product_id'].':'.($i['variant_id']?:0);}
}
