<?php
namespace App\Services;
use App\Models\CustomerModel;use App\Models\DistrictModel;use App\Models\PaymentMethodModel;use App\Models\UpazilaModel;
class OrderService
{
 private string $movementMarker='';
 public function place(array $input,array $context):array
 {
  $mobile=(new MobileNumberService())->normalize($input['mobile']??null);if(!$mobile)throw new \InvalidArgumentException('সঠিক মোবাইল নম্বর দিন।');
  $name=trim((string)($input['name']??''));$address=trim((string)($input['address_line']??''));if(mb_strlen($name)<2)throw new \InvalidArgumentException('আপনার নাম লিখুন।');if(mb_strlen($address)<5)throw new \InvalidArgumentException('সম্পূর্ণ ঠিকানা লিখুন।');
  $district=(new DistrictModel())->where(['id'=>(int)($input['district_id']??0),'status'=>'active'])->first();$upazila=(new UpazilaModel())->where(['id'=>(int)($input['upazila_id']??0),'district_id'=>(int)($district['id']??0),'status'=>'active'])->first();if(!$district)throw new \InvalidArgumentException('জেলা নির্বাচন করুন।');if(!$upazila)throw new \InvalidArgumentException('উপজেলা নির্বাচন করুন।');
  $method=(new PaymentMethodModel())->where(['id'=>(int)($input['payment_method_id']??0),'status'=>'active'])->first();if(!$method)throw new \InvalidArgumentException('পেমেন্ট পদ্ধতি নির্বাচন করুন।');$transaction=trim((string)($input['transaction_id']??''));if(in_array($method['type'],['manual_mobile_banking','courier_condition'],true)&&$transaction==='')throw new \InvalidArgumentException($method['type']==='courier_condition'?'ডেলিভারি চার্জের পেমেন্ট ট্রানজেকশন আইডি লিখুন।':'ট্রানজেকশন আইডি লিখুন।');
  if($method['code']==='cod'&&!db_connect()->table('payment_method_upazilas')->where(['payment_method_id'=>$method['id'],'upazila_id'=>$upazila['id']])->get()->getRowArray())throw new \InvalidArgumentException('নির্বাচিত উপজেলা / থানায় Cash on Delivery সেবা চালু নেই। অন্য পেমেন্ট পদ্ধতি নির্বাচন করুন।');
  $token=(string)($input['checkout_token']??'');if(!preg_match('/^[a-f0-9]{64}$/',$token))throw new \RuntimeException('চেকআউট সেশনটি মেয়াদোত্তীর্ণ। আবার চেষ্টা করুন।');
  $cart=new CartService();$resolved=$context['resolved']??($context['mode']==='buy_now'?$cart->one($context['item']):$cart->resolve());if(!$resolved['items']||$resolved['errors'])throw new \RuntimeException($resolved['errors'][0]??'কার্ট খালি।');
  if($method['type']==='manual_bank_transfer'&&$transaction==='')throw new \InvalidArgumentException('Enter the bank deposit or transfer reference.');if(mb_strlen($transaction)>100)throw new \InvalidArgumentException('Payment reference is too long.');
  $db=db_connect();$db->transException(true)->transStart();$existing=$db->table('orders')->where('checkout_token',$token)->get()->getRowArray();if($existing){$db->transComplete();return $existing;}$this->movementMarker='checkout:'.$token;
  $snapshots=[];$subtotal=0;foreach($resolved['items'] as $item){$snapshot=$this->lockAndSnapshot($db,$item);$snapshots[]=$this->markStockDeduction($db,$snapshot);$subtotal+=(float)$snapshot['subtotal'];}
  $delivery=(new DeliveryService())->calculate((int)$district['id'],(int)$upazila['id'],$subtotal);$now=date('Y-m-d H:i:s');$customerId=session('customer_logged_in')?(int)session('customer_id'):null;
  if(isset($context['customer_id'])){$customer=$db->table('customers')->where(['id'=>(int)$context['customer_id'],'deleted_at'=>null])->get()->getRowArray();if(!$customer)throw new \InvalidArgumentException('Selected customer was not found.');$customerId=(int)$customer['id'];$name=$customer['full_name'];$mobile=$customer['mobile'];}
  if(!empty($context['create_customer'])){$customer=$db->table('customers')->where(['mobile'=>$mobile,'deleted_at'=>null])->get()->getRowArray();if($customer)$customerId=(int)$customer['id'];else{$password=(string)($context['customer_password']??'');if(strlen($password)<6)throw new \InvalidArgumentException('A temporary customer password of at least 6 characters is required.');$db->table('customers')->insert(['customer_code'=>'PENDING-'.bin2hex(random_bytes(6)),'full_name'=>$name,'mobile'=>$mobile,'password_hash'=>password_hash($password,PASSWORD_DEFAULT),'status'=>'active','created_at'=>$now,'updated_at'=>$now]);$customerId=(int)$db->insertID();$db->table('customers')->where('id',$customerId)->update(['customer_code'=>sprintf('TAH-CUS-%06d',$customerId)]);}}
  $orderNo='TAH-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(4)));$publicToken=bin2hex(random_bytes(32));$paymentStatus=$method['type']==='cod'?'unpaid':'pending_verification';
  $source=in_array($context['source']??'web',['web','admin'],true)?$context['source']:'web';$db->table('orders')->insert(['order_no'=>$orderNo,'public_token'=>$publicToken,'checkout_token'=>$token,'customer_id'=>$customerId?:null,'customer_name'=>$name,'customer_mobile'=>$mobile,'district_id'=>$district['id'],'district_name'=>$district['name_bn']?:$district['name_en'],'upazila_id'=>$upazila['id'],'upazila_name'=>$upazila['name_bn']?:$upazila['name_en'],'area'=>trim((string)($input['area']??''))?:null,'address_line'=>$address,'landmark'=>trim((string)($input['landmark']??''))?:null,'subtotal'=>$subtotal,'discount'=>0,'delivery_charge'=>$delivery['charge'],'grand_total'=>$subtotal+$delivery['charge'],'payment_method_id'=>$method['id'],'payment_method_code'=>$method['code'],'payment_status'=>$paymentStatus,'order_status'=>'pending','customer_note'=>trim((string)($input['customer_note']??''))?:null,'admin_note'=>trim((string)($input['admin_note']??''))?:null,'source'=>$source,'ip_address'=>service('request')->getIPAddress(),'user_agent'=>substr((string)service('request')->getUserAgent(),0,255),'placed_at'=>$now,'created_at'=>$now,'updated_at'=>$now]);$orderId=(int)$db->insertID();
  foreach($snapshots as $snapshot){$components=$snapshot['components']??[];unset($snapshot['components']);$snapshot['order_id']=$orderId;$snapshot['created_at']=$now;$db->table('order_items')->insert($snapshot);$orderItemId=(int)$db->insertID();foreach($components as $component)$db->table('order_item_components')->insert($component+['order_item_id'=>$orderItemId,'created_at'=>$now]);}
  $paymentAmount=$method['type']==='courier_condition'?$delivery['charge']:$subtotal+$delivery['charge'];$db->table('payments')->insert(['order_id'=>$orderId,'payment_method_id'=>$method['id'],'amount'=>$paymentAmount,'currency'=>'BDT','status'=>$paymentStatus,'transaction_id'=>$transaction?:null,'sender_mobile'=>(new MobileNumberService())->normalize($input['sender_mobile']??null),'created_at'=>$now,'updated_at'=>$now]);$db->table('order_status_history')->insert(['order_id'=>$orderId,'to_status'=>'pending','note'=>$source==='admin'?'Order created by admin':'Order placed','changed_by_admin_id'=>$source==='admin'?(session('admin_id')?:null):null,'changed_by_customer_id'=>$source==='web'?($customerId?:null):null,'created_at'=>$now]);
  $db->table('inventory_movements')->where(['reference_type'=>'order_pending','note'=>$this->movementMarker])->update(['reference_type'=>'order','reference_id'=>$orderId,'note'=>'Order '.$orderNo.' stock deduction']);$db->transComplete();
  try{(new SmsService())->trigger($orderId,'placed');}catch(\Throwable $e){log_message('error','Order SMS enqueue failed: {error}',['error'=>$e->getMessage()]);}
  return $db->table('orders')->where('id',$orderId)->get()->getRowArray();
 }
 private function lockAndSnapshot($db,array $item):array
 {
  $q=(int)$item['quantity'];$now=date('Y-m-d H:i:s');if($item['item_type']==='package'){$pkg=$db->query('SELECT * FROM '.$db->prefixTable('product_packages').' WHERE id=? AND status=? AND deleted_at IS NULL FOR UPDATE',[$item['package_id'],'active'])->getRowArray();if(!$pkg)throw new \RuntimeException('প্যাকটি আর পাওয়া যাচ্ছে না।');$parts=$db->table('product_package_items ppi')->select('ppi.*,p.name,p.sku AS product_sku,p.purchase_cost,p.manage_stock,p.allow_backorder,p.status AS product_status,p.deleted_at AS product_deleted,v.variant_name,v.sku AS variant_sku,v.purchase_cost AS variant_cost,v.status AS variant_status,v.deleted_at AS variant_deleted')->join('products p','p.id=ppi.product_id')->join('product_variants v','v.id=ppi.variant_id','left')->where('ppi.package_id',$pkg['id'])->get()->getResultArray();$components=[];foreach($parts as $part){if($part['product_status']!=='active'||$part['product_deleted'])throw new \RuntimeException('প্যাকের একটি পণ্য পাওয়া যাচ্ছে না।');$needed=$q*(int)$part['quantity'];$table=$part['variant_id']?'product_variants':'products';$id=$part['variant_id']?:$part['product_id'];$stock=$db->query('SELECT * FROM '.$db->prefixTable($table).' WHERE id=? FOR UPDATE',[$id])->getRowArray();if(!$stock||($part['variant_id']&&($part['variant_status']!=='active'||$part['variant_deleted'])))throw new \RuntimeException('প্যাকের একটি অপশন পাওয়া যাচ্ছে না।');$managed=$part['variant_id']||$stock['manage_stock'];if($managed){if((int)$stock['stock_quantity']<$needed&&!(!$part['variant_id']&&$stock['allow_backorder']))throw new \RuntimeException($part['name'].'-এর পর্যাপ্ত স্টক নেই।');$this->deduct($db,$table,(int)$id,$needed,(int)$part['product_id'],$part['variant_id']?(int)$part['variant_id']:null,$now);}$components[]=['product_id'=>$part['product_id'],'variant_id'=>$part['variant_id'],'product_name'=>$part['name'],'variant_name'=>$part['variant_name'],'sku'=>$part['variant_sku']?:$part['product_sku'],'quantity_per_package'=>$part['quantity'],'total_quantity'=>$needed,'purchase_cost_snapshot'=>$part['variant_id']?$part['variant_cost']:$part['purchase_cost']];}return ['item_type'=>'package','package_id'=>$pkg['id'],'product_id'=>null,'variant_id'=>null,'product_name'=>$pkg['name'],'variant_name'=>null,'sku'=>$pkg['package_code'],'image_path'=>$pkg['main_image'],'quantity'=>$q,'unit_price'=>$pkg['package_price'],'subtotal'=>$q*(float)$pkg['package_price'],'purchase_cost_snapshot'=>null,'components'=>$components];}
  $p=$db->query('SELECT * FROM '.$db->prefixTable('products').' WHERE id=? AND status=? AND deleted_at IS NULL FOR UPDATE',[$item['product_id'],'active'])->getRowArray();if(!$p)throw new \RuntimeException('পণ্যটি আর পাওয়া যাচ্ছে না।');$v=null;if($p['stock_type']==='variant'){$v=$db->query('SELECT * FROM '.$db->prefixTable('product_variants').' WHERE id=? AND product_id=? AND status=? AND deleted_at IS NULL FOR UPDATE',[$item['variant_id'],$p['id'],'active'])->getRowArray();if(!$v)throw new \RuntimeException('অপশনটি আর পাওয়া যাচ্ছে না।');}$target=$v?:$p;if(($v||$p['manage_stock'])&&(int)$target['stock_quantity']<$q&&!(!$v&&$p['allow_backorder']))throw new \RuntimeException($p['name'].'-এর পর্যাপ্ত স্টক নেই।');if($v||$p['manage_stock'])$this->deduct($db,$v?'product_variants':'products',(int)$target['id'],$q,(int)$p['id'],$v?(int)$v['id']:null,$now);$price=(new ProductService())->effectivePrice($target);return ['item_type'=>'product','product_id'=>$p['id'],'variant_id'=>$v['id']??null,'package_id'=>null,'product_name'=>$p['name'],'variant_name'=>$v['variant_name']??null,'sku'=>$v['sku']??$p['sku'],'image_path'=>$p['main_image'],'quantity'=>$q,'unit_price'=>$price,'subtotal'=>$price*$q,'purchase_cost_snapshot'=>$target['purchase_cost'],'components'=>[]];
 }
 private function markStockDeduction($db,array $snapshot):array
 {
  if($snapshot['item_type']==='package'){
   $snapshot['stock_deducted']=0;
   foreach($snapshot['components'] as &$component){
    $component['stock_deducted']=$component['variant_id']?1:(int)($db->table('products')->select('manage_stock')->where('id',$component['product_id'])->get()->getRow('manage_stock')??0);
   }
   unset($component);
   return $snapshot;
  }
  $snapshot['stock_deducted']=$snapshot['variant_id']?1:(int)($db->table('products')->select('manage_stock')->where('id',$snapshot['product_id'])->get()->getRow('manage_stock')??0);
  return $snapshot;
 }
 private function deduct($db,string $table,int $id,int $qty,int $productId,?int $variantId,string $now):void{(new InventoryService())->moveOrderStock($db,$table,$id,-$qty,$productId,$variantId,'sale','order_pending',null,$this->movementMarker);}
}
