<?php
namespace App\Controllers\Admin;
use App\Controllers\BaseController; use App\Models\AdminRoleModel; use App\Models\AdminUserModel; use App\Services\ActivityLogService;
class AdminUserController extends BaseController
{
    public function index() { return view('admin/admin_users/index',['title'=>'Admin Users','admins'=>(new AdminUserModel())->withRole()->orderBy('admin_users.id','DESC')->findAll()]); }
    public function create() { return view('admin/admin_users/form',['title'=>'Create Admin','admin'=>null,'roles'=>(new AdminRoleModel())->findAll()]); }
    public function store() { return $this->save(null); }
    public function edit(int $id) { $admin=(new AdminUserModel())->find($id); if(!$admin) throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound(); return view('admin/admin_users/form',['title'=>'Edit Admin','admin'=>$admin,'roles'=>(new AdminRoleModel())->findAll()]); }
    public function update(int $id) { return $this->save($id); }
    private function save(?int $id) { $model=new AdminUserModel(); $rules=['name'=>'required|min_length[2]|max_length[150]','email'=>'required|valid_email|max_length[190]','role_id'=>'required|is_natural_no_zero|is_not_unique[admin_roles.id]','status'=>'required|in_list[active,inactive,blocked]']; $password=(string)$this->request->getPost('password'); if(!$id || $password!=='') $rules['password']='required|min_length[8]|max_length[255]'; if(!$this->validate($rules)) return redirect()->back()->withInput()->with('errors',$this->validator->getErrors()); $email=strtolower(trim((string)$this->request->getPost('email'))); $duplicate=$model->where('email',$email); if($id) $duplicate->where('id !=',$id); if($duplicate->first()) return redirect()->back()->withInput()->with('errors',['email'=>'This email is already registered.']); $data=['name'=>trim((string)$this->request->getPost('name')),'email'=>$email,'mobile'=>trim((string)$this->request->getPost('mobile'))?:null,'role_id'=>(int)$this->request->getPost('role_id'),'status'=>$this->request->getPost('status')]; if($id) { $current=$model->withRole()->where('admin_users.id',$id)->first(); $newRole=(new AdminRoleModel())->find($data['role_id']); $wouldRemoveSuper=$current['role_slug']==='super_admin' && ($newRole['slug']!=='super_admin' || $data['status']!=='active'); if($wouldRemoveSuper && $this->activeSuperAdminCount()<=1)return redirect()->back()->withInput()->with('danger','The last active super admin cannot be demoted or disabled.'); } if($id===(int)session('admin_id')) { $data['role_id']=$current['role_id']; $data['status']='active'; } if($password!=='') $data['password_hash']=password_hash($password,PASSWORD_DEFAULT); $id ? $model->update($id,$data) : $id=(int)$model->insert($data,true); (new ActivityLogService())->log($this->request->getPost('_method')==='PUT'?'admin_user.update':'admin_user.create','admin_users','Admin user saved.',['admin_user_id'=>$id]); return redirect()->to(route_to('admin.users'))->with('success','Admin user saved successfully.'); }
    private function activeSuperAdminCount(): int { return (new AdminUserModel())->join('admin_roles','admin_roles.id=admin_users.role_id')->where(['admin_roles.slug'=>'super_admin','admin_users.status'=>'active'])->countAllResults(); }
    public function delete(int $id) { if($id===(int)session('admin_id')) return redirect()->back()->with('danger','You cannot delete your own account.'); $model=new AdminUserModel(); $admin=$model->withRole()->where('admin_users.id',$id)->first(); if(!$admin) throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound(); if($admin['role_slug']==='super_admin' && (new AdminUserModel())->join('admin_roles','admin_roles.id=admin_users.role_id')->where('admin_roles.slug','super_admin')->countAllResults()<=1) return redirect()->back()->with('danger','The last super admin cannot be deleted.'); $model->delete($id); (new ActivityLogService())->log('admin_user.delete','admin_users','Admin user deleted.',['admin_user_id'=>$id]); return redirect()->back()->with('success','Admin user deleted successfully.'); }
}
