<?php
namespace App\Controllers\Admin;
use App\Controllers\BaseController; use App\Models\ProductCategoryModel; use App\Models\ProductModel; use App\Services\ActivityLogService; use App\Services\ImageUploadService; use App\Services\SlugService;
class CategoryController extends BaseController
{
    public function index(){ $m=new ProductCategoryModel();$q=trim((string)$this->request->getGet('q'));$status=(string)$this->request->getGet('status');$parent=(int)$this->request->getGet('parent_id');if($q)$m->like('name',$q);if(in_array($status,['active','inactive'],true))$m->where('status',$status);if($parent)$m->where('parent_id',$parent);$rows=$m->orderBy('sort_order')->orderBy('name')->paginate(20);$db=db_connect();foreach($rows as &$row){$row['parent_name']=$row['parent_id']?(new ProductCategoryModel())->find($row['parent_id'])['name']??null:null;$row['products_count']=$db->table('products')->where(['category_id'=>$row['id'],'deleted_at'=>null])->countAllResults();}return view('admin/categories/index',['title'=>'Categories','categories'=>$rows,'parents'=>(new ProductCategoryModel())->orderBy('name')->findAll(),'pager'=>$m->pager,'q'=>$q,'status'=>$status,'parent'=>$parent]); }
    public function create(){return view('admin/categories/form',['title'=>'Create Category','category'=>null,'parents'=>(new ProductCategoryModel())->orderBy('name')->findAll()]);}
    public function store(){return $this->save(null);}
    public function edit(int $id){$category=(new ProductCategoryModel())->find($id);if(!$category)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();return view('admin/categories/form',['title'=>'Edit Category','category'=>$category,'parents'=>(new ProductCategoryModel())->where('id !=',$id)->orderBy('name')->findAll()]);}
    public function update(int $id){return $this->save($id);}
    private function save(?int $id){if(!$this->validate(['name'=>'required|min_length[2]|max_length[150]','status'=>'required|in_list[active,inactive]','sort_order'=>'permit_empty|integer','parent_id'=>'permit_empty|is_natural_no_zero|is_not_unique[product_categories.id]']))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$parent=(int)$this->request->getPost('parent_id')?:null;if($id && ($parent===$id || $this->isDescendant($parent,$id)))return redirect()->back()->withInput()->with('danger','A category cannot be its own parent or create a circular hierarchy.');$m=new ProductCategoryModel();$data=['parent_id'=>$parent,'name'=>trim((string)$this->request->getPost('name')),'slug'=>(new SlugService())->unique($m,(string)($this->request->getPost('slug')?:$this->request->getPost('name')),$id),'description'=>trim((string)$this->request->getPost('description'))?:null,'icon'=>trim((string)$this->request->getPost('icon'))?:null,'sort_order'=>(int)$this->request->getPost('sort_order'),'status'=>$this->request->getPost('status'),'seo_title'=>trim((string)$this->request->getPost('seo_title'))?:null,'seo_description'=>trim((string)$this->request->getPost('seo_description'))?:null];try{$image=(new ImageUploadService())->store($this->request->getFile('image'),'categories');if($image)$data['image']=$image;}catch(\RuntimeException $e){return redirect()->back()->withInput()->with('danger',$e->getMessage());}$id?$m->update($id,$data):$id=(int)$m->insert($data,true);(new ActivityLogService())->log($this->request->getPost('_method')==='PUT'?'category.update':'category.create','categories','Category saved.',['category_id'=>$id]);return redirect()->to(url_to('admin.categories'))->with('success','Category saved successfully.');}
    private function isDescendant(?int $parent, int $id): bool { $m=new ProductCategoryModel();$seen=[];while($parent){if($parent===$id||isset($seen[$parent]))return true;$seen[$parent]=true;$parent=(int)($m->find($parent)['parent_id']??0);}return false;}
    public function status(int $id){$status=(string)$this->request->getPost('status');if(!in_array($status,['active','inactive'],true))return redirect()->back()->with('danger','Invalid status.');(new ProductCategoryModel())->update($id,['status'=>$status]);return redirect()->back()->with('success','Category status updated.');}
    public function delete(int $id){if((new ProductModel())->where('category_id',$id)->countAllResults()>0)return redirect()->back()->with('danger','Move assigned products before deleting this category.');if((new ProductCategoryModel())->where('parent_id',$id)->countAllResults()>0)return redirect()->back()->with('danger','Move child categories before deleting this category.');(new ProductCategoryModel())->delete($id);(new ActivityLogService())->log('category.delete','categories','Category deleted.',['category_id'=>$id]);return redirect()->back()->with('success','Category deleted successfully.');}
}
