<?php
namespace App\Controllers\Admin;
use App\Controllers\BaseController;use App\Models\GuideCategoryModel;use App\Models\GuideModel;use App\Services\SlugService;use App\Services\ImageUploadService;use App\Services\ActivityLogService;
class GuideCategoryController extends BaseController {
 public function index(){ $m=new GuideCategoryModel();$q=trim((string)$this->request->getGet('q'));$status=(string)$this->request->getGet('status');if($q)$m->like('name',$q);if(in_array($status,['active','inactive'],true))$m->where('status',$status);return view('admin/guides/categories/index',['title'=>'Guide Categories','rows'=>$m->orderBy('sort_order')->paginate(20),'pager'=>$m->pager,'q'=>$q,'status'=>$status]);}
 public function create(){return $this->form();}public function edit(int $id){return $this->form($id);}private function form(?int $id=null){$row=$id?(new GuideCategoryModel())->find($id):null;if($id&&!$row)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();return view('admin/guides/categories/form',['title'=>$id?'Edit Guide Category':'New Guide Category','row'=>$row,'parents'=>(new GuideCategoryModel())->where('id !=',$id??0)->orderBy('name')->findAll()]);}
 public function store(){return $this->save();}public function update(int $id){return $this->save($id);}private function save(?int $id=null){$m=new GuideCategoryModel();if($id&&!$m->find($id))throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();if(!$this->validate(['name'=>'required|min_length[2]|max_length[150]','status'=>'required|in_list[active,inactive]','sort_order'=>'permit_empty|integer']))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$parent=(int)$this->request->getPost('parent_id')?:null;$seen=[];$p=$parent;while($p){if($p===$id||isset($seen[$p]))return redirect()->back()->withInput()->with('danger','Circular category hierarchy.');$seen[$p]=true;$entry=$m->find($p);if(!$entry)return redirect()->back()->withInput()->with('danger','Invalid parent category.');$p=(int)$entry['parent_id'];}$data=['parent_id'=>$parent,'name'=>trim((string)$this->request->getPost('name')),'slug'=>(new SlugService())->unique($m,(string)($this->request->getPost('slug')?:$this->request->getPost('name')),$id),'description'=>trim((string)$this->request->getPost('description'))?:null,'status'=>$this->request->getPost('status'),'sort_order'=>(int)$this->request->getPost('sort_order'),'seo_title'=>trim((string)$this->request->getPost('seo_title'))?:null,'seo_description'=>trim((string)$this->request->getPost('seo_description'))?:null];try{$image=(new ImageUploadService())->store($this->request->getFile('image'),'guides/categories');if($image)$data['image']=$image;}catch(\RuntimeException $e){return redirect()->back()->withInput()->with('danger',$e->getMessage());}$id?$m->update($id,$data):$id=(int)$m->insert($data,true);(new ActivityLogService())->log('guide_category.save','guides','Guide category saved.',['id'=>$id]);return redirect()->to(url_to('admin.guide.categories'))->with('success','Saved.');}
 public function delete(int $id){if((new GuideCategoryModel())->where('parent_id',$id)->countAllResults()||(new GuideModel())->where('category_id',$id)->countAllResults())return redirect()->back()->with('danger','Move child categories and guides first.');(new GuideCategoryModel())->delete($id);(new ActivityLogService())->log('guide_category.delete','guides','Guide category deleted.',['id'=>$id]);return redirect()->back()->with('success','Deleted.');}
}
