<?php
namespace App\Controllers\Admin;
use App\Controllers\BaseController; use App\Models\ProductModel; use App\Models\ProductPackageItemModel; use App\Models\ProductPackageModel; use App\Models\ProductVariantModel; use App\Services\ActivityLogService; use App\Services\ImageUploadService; use App\Services\PackageService;
class PackageController extends BaseController
{
    public function index(){ $m=new ProductPackageModel();$q=trim((string)$this->request->getGet('q'));$status=(string)$this->request->getGet('status');if($q)$m->groupStart()->like('name',$q)->orLike('package_code',$q)->groupEnd();if(in_array($status,['draft','active','inactive'],true))$m->where('status',$status);$rows=$m->orderBy('id','DESC')->paginate(20);$service=new PackageService();foreach($rows as &$row)$row['available']=$service->getPackageAvailableQuantity($row['id']);return view('admin/packages/index',['title'=>'Packages','packages'=>$rows,'pager'=>$m->pager,'q'=>$q,'status'=>$status]);}
    public function create(){return $this->form(null);} public function edit(int $id){$p=(new ProductPackageModel())->find($id);if(!$p)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();return $this->form($p);}
    private function form(?array $package){$id=(int)($package['id']??0);$products=(new ProductModel())->whereIn('status',['active','draft'])->orderBy('name')->findAll();$variants=(new ProductVariantModel())->where('status','active')->orderBy('variant_name')->findAll();return view('admin/packages/form',['title'=>$id?'Edit Package':'Create Package','package'=>$package,'items'=>$id?(new ProductPackageItemModel())->where('package_id',$id)->orderBy('sort_order')->findAll():[],'products'=>$products,'variants'=>$variants,'available'=>$id?(new PackageService())->getPackageAvailableQuantity($id):0]);}
    public function store(){return $this->save(null);}public function update(int $id){return $this->save($id);}
    private function save(?int $id){if(!$this->validate(['name'=>'required|min_length[2]|max_length[190]','package_price'=>'required|decimal|greater_than_equal_to[0]','status'=>'required|in_list[draft,active,inactive]']))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$data=['name'=>trim((string)$this->request->getPost('name')),'slug'=>trim((string)$this->request->getPost('slug')),'short_description'=>trim((string)$this->request->getPost('short_description'))?:null,'description'=>trim((string)$this->request->getPost('description'))?:null,'package_price'=>(float)$this->request->getPost('package_price'),'featured'=>(bool)$this->request->getPost('featured'),'status'=>$this->request->getPost('status'),'seo_title'=>trim((string)$this->request->getPost('seo_title'))?:null,'seo_description'=>trim((string)$this->request->getPost('seo_description'))?:null,'sort_order'=>(int)$this->request->getPost('sort_order')];try{$image=(new ImageUploadService())->store($this->request->getFile('main_image'),'packages');if($image)$data['main_image']=$image;$id=(new PackageService())->save($id,$data,$this->request->getPost('items')??[]);}catch(\Throwable $e){return redirect()->back()->withInput()->with('danger',$e->getMessage());}(new ActivityLogService())->log($this->request->getPost('_method')==='PUT'?'package.update':'package.create','packages','Package saved.',['package_id'=>$id]);return redirect()->to(url_to('admin.packages'))->with('success','Package saved successfully.');}
    public function delete(int $id){(new ProductPackageModel())->delete($id);(new ActivityLogService())->log('package.delete','packages','Package deleted.',['package_id'=>$id]);return redirect()->to(url_to('admin.packages'))->with('success','Package deleted.');}
    public function recalculate(int $id){$service=new PackageService();(new ProductPackageModel())->update($id,['regular_total'=>$service->calculateRegularTotal($id)]);return redirect()->back()->with('success','Package total recalculated.');}
}
