<?= $this->extend('admin/layouts/main') ?>
<?= $this->section('content') ?>
<h1 class="h3 mb-4">Inventory</h1>
<form class="card border-0 p-3 mb-3" method="get"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="q" value="<?= esc($filters['q']) ?>" placeholder="Product, variant, or SKU"></div><div class="col-md-3"><select class="form-select" name="category_id"><option value="">All categories</option><?php foreach($categories as $c): ?><option value="<?= $c['id'] ?>" <?= $filters['category']===$c['id']?'selected':'' ?>><?= esc($c['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="type"><option value="">All types</option><option value="simple" <?= $filters['type']==='simple'?'selected':'' ?>>Simple</option><option value="variant" <?= $filters['type']==='variant'?'selected':'' ?>>Variant</option></select></div><div class="col-md-2"><select class="form-select" name="stock"><option value="">All stock</option><option value="low" <?= $filters['stock']==='low'?'selected':'' ?>>Low stock</option><option value="out" <?= $filters['stock']==='out'?'selected':'' ?>>Out of stock</option></select></div><div class="col-md-1"><button class="btn btn-success w-100">Go</button></div></div></form>
<div class="card border-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Product</th><th>Variant</th><th>SKU</th><th>Stock</th><th>Threshold</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php foreach($items as $item): ?><?php $state=$stockService->stockStatus($item['stock_quantity'],$item['low_stock_threshold']);$kind=$item['variant_id']?'variant':'product';$id=$item['variant_id']?:$item['product_id']; ?><tr><td><?= esc($item['product_name']) ?></td><td><?= esc($item['variant_name']?:'—') ?></td><td><?= esc($item['sku']?:'—') ?></td><td><?= $item['stock_quantity'] ?></td><td><?= $item['low_stock_threshold'] ?></td><td><span class="badge text-bg-<?= $state==='in_stock'?'success':($state==='low_stock'?'warning':'danger') ?>"><?= ucwords(str_replace('_',' ',$state)) ?></span></td><td><a class="btn btn-sm btn-success" href="<?= url_to('admin.inventory.adjust',$kind,$id) ?>">Adjust</a> <a class="btn btn-sm btn-outline-secondary" href="<?= url_to('admin.inventory.history',$kind,$id) ?>">History</a></td></tr><?php endforeach ?>
<?php if(!$items): ?><tr><td colspan="7" class="text-center text-muted py-4">No inventory items found.</td></tr><?php endif ?></tbody></table></div></div>
<div class="mt-3"><?= $pagerLinks ?></div>
<?= $this->endSection() ?>
