<?= $this->extend('admin/layouts/main') ?>
<?= $this->section('content') ?>
<?php $deliveryPaid=!empty($order['delivery_charge_paid_at'])?(float)$order['delivery_charge']:0.0;$paidAmount=$order['payment_status']==='paid'?(float)$order['grand_total']:$deliveryPaid;$amountDue=max(0,(float)$order['grand_total']-$paidAmount); ?>
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 mb-1"><?= esc($order['order_no']) ?></h1><span class="badge text-bg-secondary"><?= esc($order['order_status']) ?></span> <span class="badge text-bg-info"><?= esc($order['payment_status']) ?></span><?php if($deliveryPaid&&$order['payment_status']!=='paid'): ?> <span class="badge text-bg-success">Delivery paid</span><?php endif ?></div><div class="d-flex gap-2"><a class="btn btn-success" href="<?= url_to('admin.shipments.order',$order['id']) ?>">Fulfillment</a><a class="btn btn-outline-secondary" target="_blank" href="<?= url_to('admin.orders.print',$order['id']) ?>">Print invoice</a></div></div>
<div class="alert alert-light border mb-3"><strong>Payment method:</strong> <?= esc($paymentMethod['name']??strtoupper($order['payment_method_code'])) ?><?php if(!empty($paymentMethod['instructions'])): ?><div class="small text-muted mt-1"><?= esc($paymentMethod['instructions']) ?></div><?php endif ?></div>
<div class="row g-3"><div class="col-lg-8">
<div class="card border-0 p-4 mb-3"><h2 class="h5">Items</h2><div class="d-flex px-2 pb-2 border-bottom text-muted small fw-semibold"><span style="width:3rem">S.N.</span><span class="flex-grow-1">Item</span><span>Quantity &amp; total</span></div><?php foreach($items as $index=>$item): ?><div class="border-bottom py-3 px-2 d-flex align-items-start gap-3"><strong class="text-muted" style="width:2rem"><?= $index+1 ?></strong><div class="flex-grow-1"><strong><?= esc($item['product_name']) ?></strong><?php if($item['variant_name']): ?><small class="d-block"><?= esc($item['variant_name']) ?></small><?php endif ?><?php foreach($item['components'] as $component): ?><small class="d-block text-muted">↳ <?= esc($component['product_name']) ?><?= $component['variant_name']?' — '.esc($component['variant_name']):'' ?> × <?= (int)$component['total_quantity'] ?></small><?php endforeach ?></div><span class="text-nowrap"><?= (int)$item['quantity'] ?> × <?= format_bdt($item['unit_price']) ?> = <strong><?= format_bdt($item['subtotal']) ?></strong></span></div><?php endforeach ?><dl class="row mt-3 mb-0"><dt class="col-8">Subtotal</dt><dd class="col-4 text-end"><?= format_bdt($order['subtotal']) ?></dd><dt class="col-8">Delivery</dt><dd class="col-4 text-end"><?= format_bdt($order['delivery_charge']) ?></dd><dt class="col-8">Grand total</dt><dd class="col-4 text-end fw-bold"><?= format_bdt($order['grand_total']) ?></dd><dt class="col-8 text-success">Paid</dt><dd class="col-4 text-end text-success">− <?= format_bdt($paidAmount) ?></dd><dt class="col-8 fs-5 border-top pt-2">Amount due</dt><dd class="col-4 text-end fs-5 fw-bold border-top pt-2"><?= format_bdt($amountDue) ?></dd></dl></div>
<div class="card border-0 p-4"><h2 class="h5">Order history</h2><?php foreach($history as $event): ?><p class="border-bottom pb-2"><strong><?= esc(ucfirst($event['to_status'])) ?></strong> · <?= esc($event['created_at']) ?><?php if($event['note']): ?><small class="d-block text-muted"><?= esc($event['note']) ?></small><?php endif ?></p><?php endforeach ?></div></div>
<aside class="col-lg-4"><div class="card border-0 p-4 mb-3"><h2 class="h5">Customer & delivery</h2><p><strong><?= esc($order['customer_name']) ?></strong><br><?= esc($order['customer_mobile']) ?></p><p><?= esc($order['address_line']) ?><br><?= esc(implode(', ',array_filter([$order['area'],$order['upazila_name'],$order['district_name']]))) ?></p><?php if($order['customer_note']): ?><p><strong>Customer note:</strong><br><?= esc($order['customer_note']) ?></p><?php endif ?></div>
<div class="card border-0 p-4 mb-3"><h2 class="h5">Courier fulfillment</h2><?php if($shipment): ?><p><?= esc($shipment['status']) ?> · <?= esc($shipment['tracking_number']?:'No tracking number yet') ?></p><?php else: ?><p class="text-muted">No shipment prepared.</p><?php endif ?><a class="btn btn-outline-success" href="<?= url_to('admin.shipments.order',$order['id']) ?>">Manage shipment</a></div>
<?php if($transitions): ?><form class="card border-0 p-4 mb-3" method="post" action="<?= site_url('admin/orders/'.$order['id'].'/status') ?>"><?= csrf_field() ?><h2 class="h5">Change order status</h2><?php if(in_array('shipped',$transitions,true)&&(!$shipment||!in_array($shipment['status'],['booked','picked_up','in_transit','delivered'],true))): ?><div class="alert alert-warning small">Book a shipment before marking this order shipped.</div><?php endif ?><select class="form-select mb-2" name="status" required><?php foreach($transitions as $status): ?><option value="<?= $status ?>"><?= ucfirst($status) ?></option><?php endforeach ?></select><textarea class="form-control mb-2" name="note" placeholder="Optional note"></textarea><button class="btn btn-success">Update</button></form><?php endif ?>
<form class="card border-0 p-4 mb-3" method="post" action="<?= site_url('admin/orders/'.$order['id'].'/delivery-payment') ?>"><?= csrf_field() ?><h2 class="h5">Delivery charge payment</h2><div class="d-flex justify-content-between mb-2"><span>Charge</span><strong><?= format_bdt($order['delivery_charge']) ?></strong></div><div class="d-flex justify-content-between mb-3"><span>Updated invoice due</span><strong class="<?= $amountDue?'text-danger':'text-success' ?>"><?= format_bdt($amountDue) ?></strong></div><?php if($deliveryPaid): ?><div class="alert alert-success py-2 small">Paid on <?= esc($order['delivery_charge_paid_at']) ?>. Only the product balance remains due.</div><button class="btn btn-outline-danger" name="action" value="reverse">Reverse delivery payment</button><?php else: ?><p class="small text-muted">Marks only the delivery fee as paid and keeps the product balance unpaid.</p><button class="btn btn-success" name="action" value="mark_paid" <?= (float)$order['delivery_charge']<=0||$order['payment_status']==='paid'?'disabled':'' ?>>Mark delivery charge paid</button><?php endif ?></form>
<form class="card border-0 p-4 mb-3" method="post" action="<?= site_url('admin/orders/'.$order['id'].'/payment') ?>"><?= csrf_field() ?><h2 class="h5"><?= $order['payment_method_code']==='courier_condition'?'Advance delivery payment':'Full payment' ?></h2><p><?= esc($payment['status']??'N/A') ?><?php if(!empty($payment['transaction_id'])): ?><br>Reference: <?= esc($payment['transaction_id']) ?><?php endif ?><?php if($order['payment_method_code']==='courier_condition'): ?><br>Submitted amount: <?= format_bdt($payment['amount']??0) ?><?php endif ?></p><div class="d-flex gap-2"><button class="btn btn-success" name="status" value="paid"><?= $order['payment_method_code']==='courier_condition'?'Verify delivery payment':'Mark fully paid' ?></button><button class="btn btn-outline-danger" name="status" value="failed">Reject</button></div></form>
<form class="card border-0 p-4" method="post" action="<?= site_url('admin/orders/'.$order['id'].'/note') ?>"><?= csrf_field() ?><h2 class="h5">Admin note</h2><textarea class="form-control mb-2" name="admin_note" rows="3"><?= esc($order['admin_note']) ?></textarea><button class="btn btn-outline-success">Save note</button></form></aside></div>
<?= $this->endSection() ?>
