<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class CreateGuides extends Migration {
 public function up(){
 $time=['created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]];
 $this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'parent_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'name'=>['type'=>'VARCHAR','constraint'=>150],'slug'=>['type'=>'VARCHAR','constraint'=>180],'description'=>['type'=>'TEXT','null'=>true],'image'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'active'],'sort_order'=>['type'=>'INT','default'=>0],'seo_title'=>['type'=>'VARCHAR','constraint'=>190,'null'=>true],'seo_description'=>['type'=>'TEXT','null'=>true]]+$time)->addKey('id',true)->addUniqueKey('slug')->addKey('parent_id')->addForeignKey('parent_id','guide_categories','id','RESTRICT','CASCADE')->createTable('guide_categories');
 $this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'category_id'=>['type'=>'BIGINT','unsigned'=>true,'null'=>true],'title'=>['type'=>'VARCHAR','constraint'=>190],'slug'=>['type'=>'VARCHAR','constraint'=>220],'excerpt'=>['type'=>'TEXT','null'=>true],'content'=>['type'=>'LONGTEXT'],'featured_image'=>['type'=>'VARCHAR','constraint'=>255,'null'=>true],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'draft'],'featured'=>['type'=>'BOOLEAN','default'=>false],'published_at'=>['type'=>'DATETIME','null'=>true],'views'=>['type'=>'INT','unsigned'=>true,'default'=>0],'reading_time'=>['type'=>'INT','unsigned'=>true,'default'=>1],'seo_title'=>['type'=>'VARCHAR','constraint'=>190,'null'=>true],'seo_description'=>['type'=>'TEXT','null'=>true]]+$time)->addKey('id',true)->addUniqueKey('slug')->addKey('category_id')->addKey(['status','published_at'])->addForeignKey('category_id','guide_categories','id','SET NULL','CASCADE')->createTable('guides');
 foreach(['products'=>'products','packages'=>'product_packages'] as $kind=>$target){$table='guide_'.$kind;$field=$kind==='products'?'product_id':'package_id';$this->forge->addField(['guide_id'=>['type'=>'BIGINT','unsigned'=>true],$field=>['type'=>'BIGINT','unsigned'=>true]])->addKey(['guide_id',$field],true)->addForeignKey('guide_id','guides','id','CASCADE','CASCADE')->addForeignKey($field,$target,'id','CASCADE','CASCADE')->createTable($table);}
 $this->forge->addField(['id'=>['type'=>'BIGINT','unsigned'=>true,'auto_increment'=>true],'guide_id'=>['type'=>'BIGINT','unsigned'=>true],'question'=>['type'=>'VARCHAR','constraint'=>255],'answer'=>['type'=>'TEXT'],'sort_order'=>['type'=>'INT','default'=>0]])->addKey('id',true)->addKey('guide_id')->addForeignKey('guide_id','guides','id','CASCADE','CASCADE')->createTable('guide_faqs');
 $now=date('Y-m-d H:i:s');foreach(['guide_categories.view'=>'View Guide Categories','guide_categories.manage'=>'Manage Guide Categories','guides.view'=>'View Guides','guides.manage'=>'Manage Guides'] as $slug=>$name){$this->db->table('admin_permissions')->insert(['name'=>$name,'slug'=>$slug,'module'=>'guides','description'=>$name,'created_at'=>$now,'updated_at'=>$now]);$permission=$this->db->insertID();foreach(['admin','manager'] as $role){$r=$this->db->table('admin_roles')->where('slug',$role)->get()->getRowArray();if($r)$this->db->table('admin_role_permissions')->insert(['role_id'=>$r['id'],'permission_id'=>$permission,'created_at'=>$now]);}}
 }
 public function down(){foreach(['guide_faqs','guide_packages','guide_products','guides','guide_categories'] as $table)$this->forge->dropTable($table,true);foreach(['guide_categories.view','guide_categories.manage','guides.view','guides.manage'] as $slug){$p=$this->db->table('admin_permissions')->where('slug',$slug)->get()->getRowArray();if($p)$this->db->table('admin_permissions')->where('id',$p['id'])->delete();}}
}
