<article class="product-card h-100">
    <a class="product-card-image" href="<?= url_to('catalog.product', $product['slug']) ?>">
        <img src="<?= esc(store_card_image($product['main_image'] ?? null, 'product'), 'attr') ?>" width="480" height="480" loading="lazy" decoding="async" alt="<?= esc($product['name'], 'attr') ?>">
        <?php if (!$product['available']): ?><span class="stock-overlay">স্টক শেষ</span><?php elseif ($product['display_price'] < $product['display_regular_price']): ?><span class="sale-badge">সাশ্রয়</span><?php endif ?>
    </a>
    <div class="product-card-body">
        <?php if (!empty($product['category_name'])): ?><span class="eyebrow"><?= esc($product['category_name']) ?></span><?php endif ?>
        <h3><a href="<?= url_to('catalog.product', $product['slug']) ?>"><?= esc($product['name']) ?></a></h3>
        <?php if (!empty($product['review_count'])): ?><a class="product-card-rating" href="<?= url_to('catalog.product', $product['slug']) ?>#reviews">★ <?= number_format((float)$product['average_rating'], 1) ?> <span>(<?= (int)$product['review_count'] ?>)</span></a><?php endif ?>
        <?php if ($product['stock_type'] === 'variant'): ?><p class="variant-hint"><?= count($product['variants']) ?>টি অপশন</p><?php endif ?>
        <div class="price-line"><?php if ($product['price_from']): ?><small><?= lang('Store.from', [], 'bn') ?></small><?php endif ?><strong><?= format_bdt($product['display_price']) ?></strong><?php if ($product['display_price'] < $product['display_regular_price']): ?><del><?= format_bdt($product['display_regular_price']) ?></del><?php endif ?></div>
        <div class="card-footer-row"><span class="stock-text <?= $product['available'] ? 'in' : 'out' ?>"><?= !$product['available'] ? lang('Store.outOfStock', [], 'bn') : ($product['low_stock'] ? lang('Store.lowStock', [], 'bn') : lang('Store.inStock', [], 'bn')) ?></span><a class="card-cta" href="<?= url_to('catalog.product', $product['slug']) ?>">বিস্তারিত →</a></div>
        <form class="product-card-purchase" method="post" action="<?= url_to('cart.add') ?>"><?= csrf_field() ?><input type="hidden" name="item_type" value="product"><input type="hidden" name="product_id" value="<?= (int)$product['id'] ?>"><input type="hidden" name="quantity" value="1"><?php if($product['stock_type']==='variant'): ?><label class="visually-hidden" for="card-variant-<?= (int)$product['id'] ?>">অপশন নির্বাচন করুন</label><select class="product-card-variant" id="card-variant-<?= (int)$product['id'] ?>" name="variant_id" required><option value="">অপশন নির্বাচন করুন</option><?php foreach($product['variants'] as $variant): ?><option value="<?= (int)$variant['id'] ?>" <?= (int)$variant['stock_quantity']<=0?'disabled':'' ?>><?= esc($variant['variant_name']) ?><?= (int)$variant['stock_quantity']<=0?' — স্টক শেষ':'' ?></option><?php endforeach ?></select><?php endif ?><div class="product-card-buttons"><button class="card-add-button" type="submit" <?= !$product['available']?'disabled':'' ?>><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.6L20 7H6M12 9v5m-2.5-2.5h5"/></svg><span>কার্টে যোগ</span></button><button class="card-buy-button" type="submit" formaction="<?= url_to('buy.now') ?>" <?= !$product['available']?'disabled':'' ?>><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M13 3 5 14h6l-1 7 9-12h-6V3Z"/></svg><span>এখনই কিনুন</span></button></div></form>
    </div>
</article>
