<?= $this->extend('admin/layouts/main') ?>
<?= $this->section('content') ?>
<h1 class="h3"><?= esc($title) ?></h1>
<form method="post" enctype="multipart/form-data" action="<?= $row ? site_url('admin/videos/' . $row['id']) : site_url('admin/videos') ?>" class="card p-4"><input type="hidden" name="_method" value="<?= $row ? 'PUT' : 'POST' ?>"><?= csrf_field() ?><div class="row g-3">
<div class="col-md-8"><label class="form-label w-100">Title<input class="form-control" name="title" maxlength="190" value="<?= esc(old('title', $row['title'] ?? ''), 'attr') ?>" required></label></div><div class="col-md-4"><label class="form-label w-100">Slug<input class="form-control" name="slug" value="<?= esc(old('slug', $row['slug'] ?? ''), 'attr') ?>"></label></div>
<div class="col-md-8"><label class="form-label w-100">YouTube URL<input class="form-control" type="url" name="youtube_url" maxlength="500" placeholder="https://www.youtube.com/watch?v=..." value="<?= esc(old('youtube_url', $row['youtube_url'] ?? ''), 'attr') ?>" required></label></div><div class="col-md-4"><label class="form-label w-100">Duration<input class="form-control" name="duration" maxlength="20" placeholder="12:30" value="<?= esc(old('duration', $row['duration'] ?? ''), 'attr') ?>"></label></div>
<div class="col-md-5"><label class="form-label w-100">Category<select class="form-select" name="category_id"><option value="">None</option><?php foreach ($categories as $item): ?><option value="<?= $item['id'] ?>" <?= (int) old('category_id', $row['category_id'] ?? 0) === (int) $item['id'] ? 'selected' : '' ?>><?= esc($item['name']) ?></option><?php endforeach ?></select></label></div><div class="col-md-3"><label class="form-label w-100">Status<select class="form-select" name="status"><?php foreach (['draft', 'published'] as $item): ?><option value="<?= $item ?>" <?= old('status', $row['status'] ?? 'draft') === $item ? 'selected' : '' ?>><?= ucfirst($item) ?></option><?php endforeach ?></select></label></div><div class="col-md-2"><label class="form-label w-100">Sort order<input class="form-control" type="number" name="sort_order" value="<?= esc(old('sort_order', $row['sort_order'] ?? 0), 'attr') ?>"></label></div><div class="col-md-2"><label class="form-check mt-4"><input class="form-check-input" type="checkbox" name="featured" value="1" <?= old('featured', $row['featured'] ?? 0) ? 'checked' : '' ?>> Featured</label></div>
<div class="col-12"><label class="form-label w-100">Short description<textarea class="form-control" name="short_description" rows="3"><?= esc(old('short_description', $row['short_description'] ?? '')) ?></textarea></label></div>
<div class="col-12"><label class="form-label w-100">Full Bangla guide<textarea class="form-control" id="video-editor" name="content" rows="16" required><?= esc(old('content', $row['content'] ?? '')) ?></textarea></label><small>Use H2/H3 headings to structure the guide.</small></div>
<div class="col-md-6"><label class="form-label w-100">Custom thumbnail<input class="form-control" type="file" name="thumbnail" accept="image/jpeg,image/png,image/webp"></label><small class="text-muted">If omitted, the YouTube thumbnail is used.</small></div><div class="col-md-6"><label class="form-label w-100">Linked products<select class="form-select" name="product_id[]" multiple size="8"><?php foreach ($products as $product): ?><option value="<?= $product['id'] ?>" <?= in_array($product['id'], $productIds) ? 'selected' : '' ?>><?= esc($product['name']) ?></option><?php endforeach ?></select></label></div>
<div class="col-md-6"><label class="form-label w-100">SEO title<input class="form-control" name="seo_title" maxlength="190" value="<?= esc(old('seo_title', $row['seo_title'] ?? ''), 'attr') ?>"></label></div><div class="col-md-6"><label class="form-label w-100">SEO description<textarea class="form-control" name="seo_description" rows="2"><?= esc(old('seo_description', $row['seo_description'] ?? '')) ?></textarea></label></div>
</div><button class="btn btn-success mt-4">Save video</button></form>
<script src="https://cdn.jsdelivr.net/npm/tinymce@7/tinymce.min.js" referrerpolicy="origin"></script><script>tinymce.init({license_key:'gpl',selector:'#video-editor',height:500,menubar:false,plugins:'lists link',toolbar:'undo redo | blocks | bold italic | bullist numlist | link',block_formats:'Paragraph=p;Heading 2=h2;Heading 3=h3',valid_elements:'p,br,h2,h3,h4,strong,b,em,i,u,ul,ol,li,blockquote,a[href]',promotion:false});</script>
<?= $this->endSection() ?>
