<?= $this->extend('frontend/layouts/main') ?>
<?= $this->section('head') ?>
<?php $url = url_to('videos.show', $video['slug']); $thumbnail = $video['thumbnail'] ? store_image($video['thumbnail']) : 'https://i.ytimg.com/vi/' . $video['youtube_id'] . '/hqdefault.jpg'; $schema = ['@context' => 'https://schema.org', '@type' => 'VideoObject', 'name' => $video['title'], 'description' => $video['seo_description'] ?: $video['short_description'], 'thumbnailUrl' => [$thumbnail], 'embedUrl' => 'https://www.youtube-nocookie.com/embed/' . $video['youtube_id'], 'contentUrl' => $video['youtube_url'], 'uploadDate' => date(DATE_ATOM, strtotime($video['created_at']))]; ?>
<link href="<?= base_url('assets/frontend/css/videos.css') ?>" rel="stylesheet"><script type="application/ld+json"><?= json_encode($schema, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP) ?></script>
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="video-page"><div class="container"><nav class="video-breadcrumb" aria-label="Breadcrumb"><a href="<?= url_to('store.home') ?>">হোম</a><span>/</span><a href="<?= url_to('videos.index') ?>">ভিডিও</a><?php if ($category): ?><span>/</span><a href="<?= site_url('videos?category=' . rawurlencode($category['slug'])) ?>"><?= esc($category['name']) ?></a><?php endif ?><span>/</span><span aria-current="page"><?= esc($video['title']) ?></span></nav>
<header class="video-detail-header"><?php if ($category): ?><a class="video-category" href="<?= site_url('videos?category=' . rawurlencode($category['slug'])) ?>"><?= esc($category['name']) ?></a><?php endif ?><h1><?= esc($video['title']) ?></h1><?php if ($video['short_description']): ?><p><?= esc($video['short_description']) ?></p><?php endif ?><?php if ($video['duration']): ?><small>সময়: <?= esc($video['duration']) ?></small><?php endif ?></header>
<div class="video-embed"><iframe src="https://www.youtube-nocookie.com/embed/<?= esc($video['youtube_id'], 'attr') ?>?rel=0" title="<?= esc($video['title'], 'attr') ?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
<div class="video-detail-layout"><article class="video-guide"><h2>সম্পূর্ণ গাইড</h2><div class="guide-content"><?= $content ?></div></article><?php if ($toc): ?><aside class="video-toc"><h2>এই গাইডে</h2><ol><?php foreach ($toc as $item): ?><li><a href="#<?= esc($item['id'], 'attr') ?>"><?= esc($item['title']) ?></a></li><?php endforeach ?></ol></aside><?php endif ?></div></div>
<?php if ($products): ?><section class="video-products"><div class="container"><div class="video-section-heading"><div><span>ভিডিওতে ব্যবহৃত</span><h2>সম্পর্কিত পণ্য</h2></div></div><div class="product-grid"><?php foreach ($products as $product): ?><?= view('frontend/partials/product_card', ['product' => $product]) ?><?php endforeach ?></div></div></section><?php endif ?>
<?php if ($related): ?><section class="container py-5"><div class="video-section-heading"><div><span>আরও দেখুন</span><h2>সম্পর্কিত ভিডিও</h2></div><a href="<?= url_to('videos.index') ?>">সব ভিডিও →</a></div><div class="row g-4"><?php foreach ($related as $item): ?><div class="col-md-4"><?= view('frontend/videos/card', ['video' => $item]) ?></div><?php endforeach ?></div></section><?php endif ?></div>
<?= $this->endSection() ?>
